Media players
Horizontal-org/tellaweb-frontend pull request #3
Opened 2021-11-09 12:49 UTC by juandans01

2021-11-09 21:27 UTC, gmarcos87 requested changes
I haven't run it yet, the changes are on a quick read of the code. I'll see how it works and leave you another comment if necessary.

2021-11-09 21:27 UTC, gmarcos87 commented on package.json
> +    "moment": "^2.29.1",
In the project there is already date-fns as a dependency for time manage, it is a tool that solves many of the problems that momentjs has. Even momentjs recommends its use. https://momentjs.com/docs/#/-project-status/

2021-11-09 21:27 UTC, gmarcos87 commented on packages/ui/components/AudioView/AudioView.tsx
> +  }, [])
If an event is added it should be removed in the function that returns useEffect. Something like:
```suggestion
  return () => fileRef.current.removeEventListener("timeupdate", handleTimeUpdate);
  }, [])
```

2021-11-09 21:27 UTC, gmarcos87 commented on packages/ui/components/ImageView/ImageView.tsx
> +      className="w-full h-full bg-gray-25 rounded-md cursor-pointer"
You can remove some of the styling options and use tailwind's generic ones.
```suggestion
      className="w-full h-full bg-gray-25 rounded-md cursor-pointer bg-cover bg-center"
```

2021-11-09 21:27 UTC, gmarcos87 commented on packages/ui/components/MediaControls/MediaButtons.tsx
> +
```suggestion
```

2021-11-09 21:27 UTC, gmarcos87 commented on packages/ui/components/MediaControls/MediaButtons.tsx
> +  const getVolumeIcon = () => {
This should be a separate component that receives muted and volumePercentage as props. That way you also avoid storing the component as if it were state.

2021-11-09 21:27 UTC, gmarcos87 commented on packages/ui/components/MediaControls/MediaButtons.tsx
> +
```suggestion
```

2021-11-09 21:27 UTC, gmarcos87 commented on packages/ui/components/MediaControls/MediaControls.tsx
> +    console.log('fileref current')
This log can be removed

2021-11-09 21:27 UTC, gmarcos87 commented on packages/ui/components/VideoView/VideoView.tsx
> +    fileRef.current.addEventListener('canplay', () => {
Clean the listeners on the return

2021-11-09 21:27 UTC, gmarcos87 commented on packages/ui/components/VideoView/VideoView.tsx
> +    fileRef.current.addEventListener('canplay', () => {
Clean the listeners on the return

2021-11-09 22:00 UTC, gmarcos87 commented
Hi @juandans01 If you can add the storybook views for the new components that would be great! If you can't now please create the ticket in the backlog so that it is documented as a pending task.

2021-11-15 17:30 UTC, juandans01 commented
Hi Marcos! I made the changes based on your feedback
let me know what you think :)

2021-11-17 07:23 UTC, gmarcos87 requested changes
Done!, I just left some comments. Mainly that the storybook view is not working and I couldn't see how the player works. If you fix it and upload it, it would be approved immediately.

2021-11-17 07:23 UTC, gmarcos87 commented on storybook/stories/FileView.stories.tsx
> +    <div className="w-24 h24">
```suggestion
    <div className="w-24 h-24">
```
The player is not visible anyway. And the files in the mock are not audio or video, so you can't see the story correctly.

2021-11-17 07:23 UTC, gmarcos87 commented on storybook/moked/files.ts
> +    src: "",
We need to have an audio file to be able to check that it works.

2021-11-19 07:29 UTC, gmarcos87 approved these changes

2021-11-19 07:29 UTC, merged